version: "2.1"
services:
  db:
    image: mongo
    # volumes:
    #   - './data:/data/db'
    expose:
      - "27017"
      - "37017"
    command: --smallfiles
    restart: unless-stopped
  prerender:
    image: mondora/prerender
    ports:
      - "3000:3000"
    restart: unless-stopped
  web:
    build: .
    expose:
      - "80"
    env_file:
      - meanbase.env
    restart: unless-stopped
    links:
        - db:db
  nginx:
    restart: unless-stopped
    build: nginx
    links:
      - web:web
      - prerender:prerender
    volumes_from:
      - web
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - meanbase.env
    command: /bin/bash -c "envsubst '$${PRERENDER_TOKEN}' < /etc/nginx/conf.d/meanbase-nginx.template > /etc/nginx/conf.d/meanbase-nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - certs:/etc/nginx/certs
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
  letsencrypt:
    restart: unless-stopped
    container_name: letsencrypt
    image: gordonchan/auto-letsencrypt
    env_file:
      - meanbase.env
    environment:
      - SERVER_CONTAINER=letsencrypt
      - WEBROOT_PATH=/tmp/letsencrypt/www
      - CERTS_PATH=/etc/nginx/certs
      - CHECK_FREQ=7
      - LE_RENEW_HOOK=docker kill -s HUP @CONTAINER_NAME@
    volumes:
      - /var/log/letsencrypt/:/var/log/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
      - certs:/etc/nginx/certs
    links:
      - nginx
volumes:
    certs:
